[package]
name = "vm-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1.0.66"
pagemap = "0.1.0"
nix = "0.23.1"
serde = { version = "1.0", features = ["derive"] }